sudo: false
notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

env:
  matrix:
    - ATOM_CHANNEL=beta

before_install:
  - python -m pip install ipykernel --user
  - python -m ipykernel install --user
